CERTS="$(cd "$(dirname "${BASH_SOURCE[0]}")/../certs" && pwd)"
ES="https://localhost:19200"

echo -e ""
echo -e "Kibana (password login, no certificate involved): https://localhost:15601  ->  analyst:analyst"
echo -e ""
echo -e "Three identities that hold no password at all:"
echo -e ""
echo -e "  svc-logstash   CN=svc-logstash,OU=ingest,OU=Services,...   -> group 'ingest', may write logs-*"
echo -e "  svc-dashboard  CN=svc-dashboard,OU=query,OU=Services,...   -> group 'query',  may read  logs-*"
echo -e "  jsmith         CN=jsmith,OU=ingest,OU=People,...           -> refused: outside subject_dn_base"
echo -e ""
echo -e "Try them (see README.md for what each one proves):"
echo -e ""
echo -e "  # authenticated by certificate alone, and allowed to write"
echo -e "  curl -sk --cert $CERTS/svc-logstash.crt --key $CERTS/svc-logstash.key \\"
echo -e "       -XPOST $ES/logs-2026/_doc -H 'Content-Type: application/json' -d '{\"msg\":\"hello\"}'"
echo -e ""
echo -e "  # same certificate, forbidden to read - the group only grants writes"
echo -e "  curl -sk --cert $CERTS/svc-logstash.crt --key $CERTS/svc-logstash.key $ES/logs-2026/_search"
echo -e ""
echo -e "  # a different certificate, a different group, reads allowed"
echo -e "  curl -sk --cert $CERTS/svc-dashboard.crt --key $CERTS/svc-dashboard.key $ES/logs-2026/_search"
echo -e ""
echo -e "  # trusted by the same CA, but issued into the People branch - refused"
echo -e "  curl -sk --cert $CERTS/jsmith.crt --key $CERTS/jsmith.key $ES/logs-2026/_search"
echo -e ""
echo -e "  # no certificate at all: falls through to the password block on the very same port"
echo -e "  curl -sk -u analyst:analyst $ES/logs-2026/_search"
echo -e ""
echo -e "A Logstash container is already shipping to logs-2026 with the svc-logstash certificate and no"
echo -e "password. Watch what it sends, and watch a different certificate read it back:"
echo -e ""
echo -e "  docker logs -f \$(docker ps -qf name=logstash)"
echo -e ""
echo -e "  curl -sk --cert $CERTS/svc-dashboard.crt --key $CERTS/svc-dashboard.key $ES/logs-2026/_count"
echo -e ""
