echo -e "Access ROR via reverse proxy: https://localhost:8443/ror-demo"
echo -e "  kbn-ror   direct access:   https://localhost:15601/ror-demo"
echo -e "  kbn-ror-2 direct access:   https://localhost:15602/ror-demo"
echo -e ""
echo -e "Local users:"
echo -e "  admin:admin     → Administrator (full admin)"
echo -e "  user1:test      → End User + Business User"
echo -e "  user2:test      → End User"
echo -e ""
echo -e "Keycloak users (SAML/OIDC):"
echo -e "  extUser1:extUser1  → End User + Business User"
echo -e "  extUser2:extUser2  → End User"
echo -e ""
echo -e "LemonLDAP users (OpenID):"
echo -e "  dwho:dwho      → End User"
echo -e "  rtyler:rtyler  → End User"
echo -e "  msmith:msmith  → End User"
open https://localhost:8443/ror-demo
