echo -e "You can access ReadonlyREST Kibana here: https://localhost:15601"
echo -e ""
echo -e "Users:"
echo -e "  admin:admin  → Administrators + End Users + Business Users (full admin)"
echo -e "  user1:test   → End Users + Business Users"
echo -e "  user2:test   → End Users"
echo -e ""
echo -e "Fleet Server:  https://localhost:8220"
echo -e "APM Server:    http://localhost:8201"
echo -e "service1:      http://localhost:3001"
open https://localhost:15601
