services:

  proxy:
    build:
      context: ${EXAMPLE_DIR}
      dockerfile: images/reverse-proxy/Dockerfile
    depends_on:
      kbn-ror:
        condition: service_healthy
      kbn-ror-2:
        condition: service_healthy
    networks:
      - ror-network
    ports:
      - "8082:80"
      - "8443:443"
    entrypoint: ["sh", "/usr/local/bin/reverse-proxy-entrypoint.sh"]
