echo -e "You can access ReadonlyREST Kibana here: https://localhost:15601"
echo -e ""
echo -e "Users:"
echo -e "  admin:admin     Kibana admin, unrestricted"
echo -e "  analyst:analyst Kibana + MCP access to logs-* only"
echo -e ""
echo -e "MCP server (Elasticsearch MCP, ROR-secured):"
echo -e "  Endpoint: http://localhost:18080/mcp"
echo -e "  Health:   http://localhost:18080/ping"
echo -e ""
echo -e "The MCP server has no credentials of its own - every client sends its own"
echo -e "Authorization header, which is forwarded straight to Elasticsearch/ROR:"
echo -e "  claude mcp add --transport http elasticsearch-analyst http://localhost:18080/mcp \\"
echo -e "    --header \"Authorization: Basic \$(printf 'analyst:analyst' | base64)\""
echo -e ""
echo -e "Smoke test without any MCP client (lists the 5 available tools):"
echo -e "  curl -s http://localhost:18080/mcp -H 'Content-Type: application/json' \\"
echo -e "    -H 'Accept: application/json, text/event-stream' \\"
echo -e "    -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}'"

open https://localhost:15601
