echo -e "You can access ReadonlyREST Kibana here: https://localhost:15601"
echo -e ""
echo -e "Users:"
echo -e "  admin:admin     Kibana admin, can mint ES API keys"
echo -e "  analyst:analyst Kibana + MCP access to logs-* only (Authorization passthrough)"
echo -e ""
echo -e "MCP server (Elasticsearch MCP, ROR-secured):"
echo -e "  Endpoint: http://localhost:18080/mcp"
echo -e "  Health:   http://localhost:18080/ping"
echo -e ""
echo -e "Wire it into Claude Code, using the MCP server's own ES API key identity:"
echo -e "  claude mcp add --transport http elasticsearch http://localhost:18080/mcp"
echo -e ""
echo -e "Or exercise per-user access via Authorization passthrough (analyst:analyst):"
echo -e "  claude mcp add --transport http elasticsearch-analyst http://localhost:18080/mcp \\"
echo -e "    --header \"Authorization: Basic \$(printf 'analyst:analyst' | base64)\""
echo -e ""
echo -e "Smoke test without any MCP client (lists the 5 available tools):"
echo -e "  curl -s http://localhost:18080/mcp -H 'Content-Type: application/json' \\"
echo -e "    -H 'Accept: application/json, text/event-stream' \\"
echo -e "    -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}'"
open https://localhost:15601
