echo -e "You can access ReadonlyREST Kibana here: https://localhost:15601"
echo -e ""
echo -e "Users:"
echo -e "  admin:admin     Kibana admin, unrestricted"
echo -e "  analyst:analyst MCP + Kibana (read-only): logs-* and orders-*"
echo -e "  hr:hr           MCP + Kibana (read-only): hr-salaries-* and orders-*"
echo -e ""
echo -e "MCP server (Elasticsearch MCP, ROR-secured):"
echo -e "  Endpoint: http://localhost:18080/mcp"
echo -e "  Health:   http://localhost:18080/ping"
echo -e ""
echo -e "The MCP server has no credentials of its own - every client sends its own"
echo -e "Authorization header, which is forwarded straight to Elasticsearch/ROR."
echo -e "Point any MCP client at the endpoint with one of these headers:"
echo -e "  Authorization: Basic YW5hbHlzdDphbmFseXN0   # analyst:analyst"
echo -e "  Authorization: Basic aHI6aHI=               # hr:hr"
echo -e ""
echo -e "Two agents, one per MCP user (opencode, already wired to the MCP server):"
echo -e "  docker exec -it opencode-analyst opencode   # sends analyst:analyst"
echo -e "  docker exec -it opencode-hr opencode        # sends hr:hr"
echo -e ""
echo -e "  First time: run /connect in the TUI and sign in with whichever provider"
echo -e "  you use - API key, or a browser/subscription login. One sign-in covers"
echo -e "  both containers. Then ask each agent: \"which indices can you see?\""
echo -e ""
echo -e "Smoke test without any MCP client (lists the 5 available tools):"
echo -e "  curl -s http://localhost:18080/mcp -H 'Content-Type: application/json' \\"
echo -e "    -H 'Accept: application/json, text/event-stream' \\"
echo -e "    -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}'"

open https://localhost:15601
